### ISSUE TITLE
Standardwert bei Area nicht vorhanden

### ISSUE THREAD

**Issue by paresy** [Nall-chan/IPSSchoolHolidays#1]
<img width="601" alt="bildschirmfoto 2017-03-04 um 11 03 38" src="https://cloud.githubusercontent.com/assets/260376/23577878/6e7df10a-00ca-11e7-9c56-e8de885a857d.png">

**Comment by Nall-chan** [comment]
Erledigt.
Danke

**Comment by Nall-chan** [comment]
Danke.
Erledigt.
